name: Combined Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout TestHotel.API
      uses: actions/checkout@v2
      with:
        repository: MirazamTUT/TestHotel.API

    - name: Checkout TestHotel.DataAccess
      uses: actions/checkout@v2
      with:
        repository: MirazamTUT/TestHotel.DataAccess

    - name: Checkout TestHotel.Service
      uses: actions/checkout@v2
      with:
        repository: MirazamTUT/TestHotel.Service

    - name: Build and Test TestHotel.API
      run: |
        cd TestHotel.API
        # Add commands to build and test TestHotel.API here

    - name: Build and Test TestHotel.DataAccess
      run: |
        cd TestHotel.DataAccess
        # Add commands to build and test TestHotel.DataAccess here

    - name: Build and Test TestHotel.Service
      run: |
        cd TestHotel.Service
        # Add commands to build and test TestHotel.Service here
