# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: Combined Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout TestHotel.API
      uses: actions/checkout@v2
      with:
        repository: isfandiyoro5/TestHotel.API

    - name: Checkout TestHotel.DataAccess
      uses: actions/checkout@v2
      with:
        repository: isfandiyoro5/TestHotel.DataAccess

    - name: Checkout TestHotel.Service
      uses: actions/checkout@v2
      with:
        repository: isfandiyoro5/TestHotel.Service

    - name: Build and Test TestHotel.API
      run: |
        cd TestHotel.API
        # Add commands to build and test TestHotel.API here

    - name: Build and Test TestHotel.DataAccess
      run: |
        cd TestHotel.DataAccess
        # Add commands to build and test TestHotel.DataAccess here

    - name: Build and Test TestHotel.Service
      run: |
        cd TestHotel.Service
        # Add commands to build and test TestHotel.Service here
