name: Build and Deploy TestHotel

on:
  push:
    branches:
      - main

jobs:
  build-api:
    name: Build TestHotel.API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build API
        run: dotnet build ./TestHotel.API/TestHotel.API.csproj

  build-data-access:
    name: Build TestHotel DataAccess
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build DataAccess
        run: dotnet build ./TestHotel.DataAccess/TestHotel.DataAccess.csproj

  build-service:
    name: Build TestHotel Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build Service
        run: dotnet build ./TestHotel.Service/TestHotel.Service.csproj

  test-api:
    name: Test TestHotel API
    runs-on: ubuntu-latest
    needs: build-api
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Restore dependencies
        run: dotnet restore ./TestHotel.API/TestHotel.API.csproj

      - name: Run tests
        run: dotnet test ./TestHotel.API/TestHotel.API.csproj

  test-data-access:
    name: Test TestHotel DataAccess
    runs-on: ubuntu-latest
    needs: build-data-access
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Restore dependencies
        run: dotnet restore ./TestHotel.DataAccess/TestHotel.DataAccess.csproj

      - name: Run tests
        run: dotnet test ./TestHotel.DataAccess/TestHotel.DataAccess.csproj

  test-service:
    name: Test TestHotel Service
    runs-on: ubuntu-latest
    needs: build-service
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Restore dependencies
        run: dotnet restore ./TestHotel.Service/TestHotel.Service.csproj

      - name: Run tests
        run: dotnet test ./TestHotel.Service/TestHotel.Service.csproj

  deploy:
    name: Deploy TestHotel
    runs-on: ubuntu-latest
    needs:
      - test-api
      - test-data-access
      - test-service
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy to production
        uses: "appleboy/ssh-action@master"
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/testhotel
            git pull origin main
            dotnet publish -c Release
            systemctl restart testhotel.service
